version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  nodejs-app:
    image: node:18
    container_name: nodejs-app
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "index.js"]
    ports:
      - "3001:3000"
    restart: always
